steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/massive-tea-327010/online-retail-clv/dnn-regressor:latest', '.' ]
images: 
- 'us-central1-docker.pkg.dev/massive-tea-327010/online-retail-clv/dnn-regressor:latest'